//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 10 colors.
  struct color {
    /// Color `action.accent`.
    static let actionAccent = Rswift.ColorResource(bundle: R.hostingBundle, name: "action.accent")
    /// Color `background`.
    static let background = Rswift.ColorResource(bundle: R.hostingBundle, name: "background")
    /// Color `block`.
    static let block = Rswift.ColorResource(bundle: R.hostingBundle, name: "block")
    /// Color `green`.
    static let green = Rswift.ColorResource(bundle: R.hostingBundle, name: "green")
    /// Color `grey`.
    static let grey = Rswift.ColorResource(bundle: R.hostingBundle, name: "grey")
    /// Color `red`.
    static let red = Rswift.ColorResource(bundle: R.hostingBundle, name: "red")
    /// Color `shape.background`.
    static let shapeBackground = Rswift.ColorResource(bundle: R.hostingBundle, name: "shape.background")
    /// Color `text.primary`.
    static let textPrimary = Rswift.ColorResource(bundle: R.hostingBundle, name: "text.primary")
    /// Color `text.secondary`.
    static let textSecondary = Rswift.ColorResource(bundle: R.hostingBundle, name: "text.secondary")
    /// Color `yellow`.
    static let yellow = Rswift.ColorResource(bundle: R.hostingBundle, name: "yellow")
    
    /// `UIColor(named: "action.accent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func actionAccent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.actionAccent, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.background, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "block", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func block(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.block, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "green", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func green(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.green, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "grey", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func grey(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.grey, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "red", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func red(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.red, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "shape.background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shapeBackground(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shapeBackground, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "text.primary", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textPrimary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textPrimary, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "text.secondary", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textSecondary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textSecondary, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "yellow", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func yellow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.yellow, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `Config.xcconfig`.
    static let configXcconfig = Rswift.FileResource(bundle: R.hostingBundle, name: "Config", pathExtension: "xcconfig")
    
    /// `bundle.url(forResource: "Config", withExtension: "xcconfig")`
    static func configXcconfig(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.configXcconfig
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 19 images.
  struct image {
    /// Image `common.arrowDown`.
    static let commonArrowDown = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.arrowDown")
    /// Image `common.arrowUp`.
    static let commonArrowUp = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.arrowUp")
    /// Image `common.calendar`.
    static let commonCalendar = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.calendar")
    /// Image `common.details`.
    static let commonDetails = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.details")
    /// Image `common.edit`.
    static let commonEdit = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.edit")
    /// Image `common.gameCover`.
    static let commonGameCover = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.gameCover")
    /// Image `common.gamepadArrow`.
    static let commonGamepadArrow = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.gamepadArrow")
    /// Image `common.normal.crown`.
    static let commonNormalCrown = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.normal.crown")
    /// Image `common.plus`.
    static let commonPlus = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.plus")
    /// Image `common.small.crown`.
    static let commonSmallCrown = Rswift.ImageResource(bundle: R.hostingBundle, name: "common.small.crown")
    /// Image `status.normal.declined`.
    static let statusNormalDeclined = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.normal.declined")
    /// Image `status.normal.late`.
    static let statusNormalLate = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.normal.late")
    /// Image `status.normal.maybe`.
    static let statusNormalMaybe = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.normal.maybe")
    /// Image `status.normal.ontime`.
    static let statusNormalOntime = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.normal.ontime")
    /// Image `status.normal.unknown`.
    static let statusNormalUnknown = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.normal.unknown")
    /// Image `status.small.declined`.
    static let statusSmallDeclined = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.small.declined")
    /// Image `status.small.maybe`.
    static let statusSmallMaybe = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.small.maybe")
    /// Image `status.small.ontime`.
    static let statusSmallOntime = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.small.ontime")
    /// Image `status.small.unknown`.
    static let statusSmallUnknown = Rswift.ImageResource(bundle: R.hostingBundle, name: "status.small.unknown")
    
    /// `UIImage(named: "common.arrowDown", bundle: ..., traitCollection: ...)`
    static func commonArrowDown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonArrowDown, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.arrowUp", bundle: ..., traitCollection: ...)`
    static func commonArrowUp(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonArrowUp, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.calendar", bundle: ..., traitCollection: ...)`
    static func commonCalendar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonCalendar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.details", bundle: ..., traitCollection: ...)`
    static func commonDetails(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonDetails, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.edit", bundle: ..., traitCollection: ...)`
    static func commonEdit(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonEdit, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.gameCover", bundle: ..., traitCollection: ...)`
    static func commonGameCover(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonGameCover, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.gamepadArrow", bundle: ..., traitCollection: ...)`
    static func commonGamepadArrow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonGamepadArrow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.normal.crown", bundle: ..., traitCollection: ...)`
    static func commonNormalCrown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonNormalCrown, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.plus", bundle: ..., traitCollection: ...)`
    static func commonPlus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonPlus, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common.small.crown", bundle: ..., traitCollection: ...)`
    static func commonSmallCrown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commonSmallCrown, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.normal.declined", bundle: ..., traitCollection: ...)`
    static func statusNormalDeclined(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusNormalDeclined, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.normal.late", bundle: ..., traitCollection: ...)`
    static func statusNormalLate(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusNormalLate, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.normal.maybe", bundle: ..., traitCollection: ...)`
    static func statusNormalMaybe(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusNormalMaybe, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.normal.ontime", bundle: ..., traitCollection: ...)`
    static func statusNormalOntime(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusNormalOntime, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.normal.unknown", bundle: ..., traitCollection: ...)`
    static func statusNormalUnknown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusNormalUnknown, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.small.declined", bundle: ..., traitCollection: ...)`
    static func statusSmallDeclined(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusSmallDeclined, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.small.maybe", bundle: ..., traitCollection: ...)`
    static func statusSmallMaybe(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusSmallMaybe, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.small.ontime", bundle: ..., traitCollection: ...)`
    static func statusSmallOntime(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusSmallOntime, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "status.small.unknown", bundle: ..., traitCollection: ...)`
    static func statusSmallUnknown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statusSmallUnknown, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 11 nibs.
  struct nib {
    /// Nib `ActiveEventCell`.
    static let activeEventCell = _R.nib._ActiveEventCell()
    /// Nib `AvatarView`.
    static let avatarView = _R.nib._AvatarView()
    /// Nib `EventCell`.
    static let eventCell = _R.nib._EventCell()
    /// Nib `EventDetailsMemberCell`.
    static let eventDetailsMemberCell = _R.nib._EventDetailsMemberCell()
    /// Nib `InventedHeaderView`.
    static let inventedHeaderView = _R.nib._InventedHeaderView()
    /// Nib `InvitationsHeaderCell`.
    static let invitationsHeaderCell = _R.nib._InvitationsHeaderCell()
    /// Nib `InvitedEventCell`.
    static let invitedEventCell = _R.nib._InvitedEventCell()
    /// Nib `NewEventGameCell`.
    static let newEventGameCell = _R.nib._NewEventGameCell()
    /// Nib `NewEventMemberCell`.
    static let newEventMemberCell = _R.nib._NewEventMemberCell()
    /// Nib `SearchEmptyResultCell`.
    static let searchEmptyResultCell = _R.nib._SearchEmptyResultCell()
    /// Nib `SearchGameCell`.
    static let searchGameCell = _R.nib._SearchGameCell()
    
    /// `UINib(name: "ActiveEventCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.activeEventCell) instead")
    static func activeEventCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.activeEventCell)
    }
    
    /// `UINib(name: "AvatarView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.avatarView) instead")
    static func avatarView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.avatarView)
    }
    
    /// `UINib(name: "EventCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.eventCell) instead")
    static func eventCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.eventCell)
    }
    
    /// `UINib(name: "EventDetailsMemberCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.eventDetailsMemberCell) instead")
    static func eventDetailsMemberCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.eventDetailsMemberCell)
    }
    
    /// `UINib(name: "InventedHeaderView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.inventedHeaderView) instead")
    static func inventedHeaderView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.inventedHeaderView)
    }
    
    /// `UINib(name: "InvitationsHeaderCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.invitationsHeaderCell) instead")
    static func invitationsHeaderCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.invitationsHeaderCell)
    }
    
    /// `UINib(name: "InvitedEventCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.invitedEventCell) instead")
    static func invitedEventCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.invitedEventCell)
    }
    
    /// `UINib(name: "NewEventGameCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.newEventGameCell) instead")
    static func newEventGameCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newEventGameCell)
    }
    
    /// `UINib(name: "NewEventMemberCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.newEventMemberCell) instead")
    static func newEventMemberCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newEventMemberCell)
    }
    
    /// `UINib(name: "SearchEmptyResultCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.searchEmptyResultCell) instead")
    static func searchEmptyResultCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.searchEmptyResultCell)
    }
    
    /// `UINib(name: "SearchGameCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.searchGameCell) instead")
    static func searchGameCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.searchGameCell)
    }
    
    static func activeEventCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ActiveEventCell? {
      return R.nib.activeEventCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ActiveEventCell
    }
    
    static func avatarView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.avatarView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func eventCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EventCell? {
      return R.nib.eventCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EventCell
    }
    
    static func eventDetailsMemberCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EventDetailsMemberCell? {
      return R.nib.eventDetailsMemberCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EventDetailsMemberCell
    }
    
    static func inventedHeaderView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.inventedHeaderView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func invitationsHeaderCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> InvitationsHeaderCell? {
      return R.nib.invitationsHeaderCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? InvitationsHeaderCell
    }
    
    static func invitedEventCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.invitedEventCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func newEventGameCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> NewEventGameCell? {
      return R.nib.newEventGameCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewEventGameCell
    }
    
    static func newEventMemberCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> NewEventMemberCell? {
      return R.nib.newEventMemberCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewEventMemberCell
    }
    
    static func searchEmptyResultCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SearchEmptyResultCell? {
      return R.nib.searchEmptyResultCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SearchEmptyResultCell
    }
    
    static func searchGameCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SearchGameCell? {
      return R.nib.searchGameCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SearchGameCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 6 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ActiveEventCell`.
    static let activeEventCell: Rswift.ReuseIdentifier<ActiveEventCell> = Rswift.ReuseIdentifier(identifier: "ActiveEventCell")
    /// Reuse identifier `EventCell`.
    static let eventCell: Rswift.ReuseIdentifier<EventCell> = Rswift.ReuseIdentifier(identifier: "EventCell")
    /// Reuse identifier `NewEventGameCell`.
    static let newEventGameCell: Rswift.ReuseIdentifier<NewEventGameCell> = Rswift.ReuseIdentifier(identifier: "NewEventGameCell")
    /// Reuse identifier `NewEventMemberCell`.
    static let newEventMemberCell: Rswift.ReuseIdentifier<NewEventMemberCell> = Rswift.ReuseIdentifier(identifier: "NewEventMemberCell")
    /// Reuse identifier `SearchEmptyResultCell`.
    static let searchEmptyResultCell: Rswift.ReuseIdentifier<SearchEmptyResultCell> = Rswift.ReuseIdentifier(identifier: "SearchEmptyResultCell")
    /// Reuse identifier `SearchGameCell`.
    static let searchGameCell: Rswift.ReuseIdentifier<SearchGameCell> = Rswift.ReuseIdentifier(identifier: "SearchGameCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 6 storyboards.
  struct storyboard {
    /// Storyboard `EventDetails`.
    static let eventDetails = _R.storyboard.eventDetails()
    /// Storyboard `EventsList`.
    static let eventsList = _R.storyboard.eventsList()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `NewEvent`.
    static let newEvent = _R.storyboard.newEvent()
    /// Storyboard `SearchGame`.
    static let searchGame = _R.storyboard.searchGame()
    /// Storyboard `SearchMembers`.
    static let searchMembers = _R.storyboard.searchMembers()
    
    /// `UIStoryboard(name: "EventDetails", bundle: ...)`
    static func eventDetails(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.eventDetails)
    }
    
    /// `UIStoryboard(name: "EventsList", bundle: ...)`
    static func eventsList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.eventsList)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "NewEvent", bundle: ...)`
    static func newEvent(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.newEvent)
    }
    
    /// `UIStoryboard(name: "SearchGame", bundle: ...)`
    static func searchGame(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.searchGame)
    }
    
    /// `UIStoryboard(name: "SearchMembers", bundle: ...)`
    static func searchMembers(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.searchMembers)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 43 localization keys.
    struct localizable {
      /// Value: +%@ мин
      static let eventDetailsCellLateness = Rswift.StringResource(key: "eventDetails.cell.lateness", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Localizable
      static let tableName = Rswift.StringResource(key: "tableName", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Ближайшее событие
      static let eventsListSectionsActive = Rswift.StringResource(key: "eventsList.sections.active", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Будущие события
      static let eventsListSectionsFuture = Rswift.StringResource(key: "eventsList.sections.future", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Во сколько
      static let newEventChooseTimeLabelTitle = Rswift.StringResource(key: "newEvent.chooseTimeLabel.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Во что
      static let newEventChooseGameLabelTitle = Rswift.StringResource(key: "newEvent.chooseGameLabel.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Вовремя
      static let statusOntimeShort = Rswift.StringResource(key: "status.ontime.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Возможно
      static let statusMaybeShort = Rswift.StringResource(key: "status.maybe.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Возможно, пойду
      static let statusMaybeFull = Rswift.StringResource(key: "status.maybe.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Все события
      static let eventsListTitle = Rswift.StringResource(key: "eventsList.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Выбрать %@
      static let commonChoose = Rswift.StringResource(key: "common.choose", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Добавить участников
      static let eventDetailsAddMemberLabelTitle = Rswift.StringResource(key: "eventDetails.addMemberLabel.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Завтра
      static let newEventTomorrowButtonTitle = Rswift.StringResource(key: "newEvent.tomorrowButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Исключить
      static let eventMemberMenuItemDelete = Rswift.StringResource(key: "eventMemberMenuItem.delete", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Ищите игры по названию
      static let searchGameEmptySateTitle = Rswift.StringResource(key: "searchGame.emptySate.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Когда
      static let newEventChooseDayLabelTitle = Rswift.StringResource(key: "newEvent.chooseDayLabel.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Название игры
      static let searchGameSearchBarPlaceholder = Rswift.StringResource(key: "searchGame.searchBar.placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Например, введите 'Overwatch' и посмотрите, что будет =)
      static let searchGameEmptySateDescription = Rswift.StringResource(key: "searchGame.emptySate.description", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Не пойду
      static let statusDeclinedFull = Rswift.StringResource(key: "status.declined.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Не пойду
      static let statusDeclinedShort = Rswift.StringResource(key: "status.declined.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Не получилось найти игру =(
      static let searchGameEmptyResultsTitle = Rswift.StringResource(key: "searchGame.emptyResults.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Опоздаю
      static let statusLateShort = Rswift.StringResource(key: "status.late.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Опоздаю на %d мин
      static let statusLateFull = Rswift.StringResource(key: "status.late.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Отклоненные события
      static let eventsListSectionsDeclined = Rswift.StringResource(key: "eventsList.sections.declined", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Отмена
      static let commonCancel = Rswift.StringResource(key: "common.cancel", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Отмена
      static let searchGameCloseButtonTitle = Rswift.StringResource(key: "searchGame.closeButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Поиск игры
      static let newEventSearchGameButtonTitle = Rswift.StringResource(key: "newEvent.searchGameButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Поиск игры
      static let searchGameTitle = Rswift.StringResource(key: "searchGame.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Поиск участников
      static let newEventSearchMembersButtonTitle = Rswift.StringResource(key: "newEvent.searchMembersButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Пойду
      static let statusAcceptedShort = Rswift.StringResource(key: "status.accepted.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приглашен
      static let statusUnknownFull = Rswift.StringResource(key: "status.unknown.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приглашен
      static let statusUnknownShort = Rswift.StringResource(key: "status.unknown.short", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приглашения
      static let eventsListSectionsInvented = Rswift.StringResource(key: "eventsList.sections.invented", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приглашения
      static let eventsListSectionsInvited = Rswift.StringResource(key: "eventsList.sections.invited", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приду вовремя
      static let statusAcceptedFull = Rswift.StringResource(key: "status.accepted.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Приду вовремя
      static let statusOntimeFull = Rswift.StringResource(key: "status.ontime.full", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Результаты поиска
      static let searchGameSectionsSearchResults = Rswift.StringResource(key: "searchGame.sections.searchResults", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: С кем
      static let newEventChooseMembersLabelTitle = Rswift.StringResource(key: "newEvent.chooseMembersLabel.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Сделать лидером
      static let eventMemberMenuItemMakeOwner = Rswift.StringResource(key: "eventMemberMenuItem.makeOwner", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Сегодня
      static let newEventTodayButtonTitle = Rswift.StringResource(key: "newEvent.todayButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Создание события
      static let newEventTitle = Rswift.StringResource(key: "newEvent.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Создать событие
      static let newEventMainActionTitle = Rswift.StringResource(key: "newEvent.mainAction.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Частые игры
      static let searchGameSectionsOfften = Rswift.StringResource(key: "searchGame.sections.offten", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: +%@ мин
      static func eventDetailsCellLateness(_ value1: String) -> String {
        return String(format: NSLocalizedString("eventDetails.cell.lateness", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// Value: Localizable
      static func tableName(_: Void = ()) -> String {
        return NSLocalizedString("tableName", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Ближайшее событие
      static func eventsListSectionsActive(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.sections.active", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Будущие события
      static func eventsListSectionsFuture(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.sections.future", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Во сколько
      static func newEventChooseTimeLabelTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.chooseTimeLabel.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Во что
      static func newEventChooseGameLabelTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.chooseGameLabel.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Вовремя
      static func statusOntimeShort(_: Void = ()) -> String {
        return NSLocalizedString("status.ontime.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Возможно
      static func statusMaybeShort(_: Void = ()) -> String {
        return NSLocalizedString("status.maybe.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Возможно, пойду
      static func statusMaybeFull(_: Void = ()) -> String {
        return NSLocalizedString("status.maybe.full", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Все события
      static func eventsListTitle(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Выбрать %@
      static func commonChoose(_ value1: String) -> String {
        return String(format: NSLocalizedString("common.choose", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// Value: Добавить участников
      static func eventDetailsAddMemberLabelTitle(_: Void = ()) -> String {
        return NSLocalizedString("eventDetails.addMemberLabel.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Завтра
      static func newEventTomorrowButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.tomorrowButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Исключить
      static func eventMemberMenuItemDelete(_: Void = ()) -> String {
        return NSLocalizedString("eventMemberMenuItem.delete", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Ищите игры по названию
      static func searchGameEmptySateTitle(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.emptySate.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Когда
      static func newEventChooseDayLabelTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.chooseDayLabel.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Название игры
      static func searchGameSearchBarPlaceholder(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.searchBar.placeholder", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Например, введите 'Overwatch' и посмотрите, что будет =)
      static func searchGameEmptySateDescription(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.emptySate.description", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Не пойду
      static func statusDeclinedFull(_: Void = ()) -> String {
        return NSLocalizedString("status.declined.full", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Не пойду
      static func statusDeclinedShort(_: Void = ()) -> String {
        return NSLocalizedString("status.declined.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Не получилось найти игру =(
      static func searchGameEmptyResultsTitle(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.emptyResults.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Опоздаю
      static func statusLateShort(_: Void = ()) -> String {
        return NSLocalizedString("status.late.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Опоздаю на %d мин
      static func statusLateFull(_ value1: Int) -> String {
        return String(format: NSLocalizedString("status.late.full", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// Value: Отклоненные события
      static func eventsListSectionsDeclined(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.sections.declined", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Отмена
      static func commonCancel(_: Void = ()) -> String {
        return NSLocalizedString("common.cancel", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Отмена
      static func searchGameCloseButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.closeButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Поиск игры
      static func newEventSearchGameButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.searchGameButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Поиск игры
      static func searchGameTitle(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Поиск участников
      static func newEventSearchMembersButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.searchMembersButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Пойду
      static func statusAcceptedShort(_: Void = ()) -> String {
        return NSLocalizedString("status.accepted.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приглашен
      static func statusUnknownFull(_: Void = ()) -> String {
        return NSLocalizedString("status.unknown.full", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приглашен
      static func statusUnknownShort(_: Void = ()) -> String {
        return NSLocalizedString("status.unknown.short", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приглашения
      static func eventsListSectionsInvented(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.sections.invented", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приглашения
      static func eventsListSectionsInvited(_: Void = ()) -> String {
        return NSLocalizedString("eventsList.sections.invited", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приду вовремя
      static func statusAcceptedFull(_: Void = ()) -> String {
        return NSLocalizedString("status.accepted.full", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Приду вовремя
      static func statusOntimeFull(_: Void = ()) -> String {
        return NSLocalizedString("status.ontime.full", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Результаты поиска
      static func searchGameSectionsSearchResults(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.sections.searchResults", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: С кем
      static func newEventChooseMembersLabelTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.chooseMembersLabel.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Сделать лидером
      static func eventMemberMenuItemMakeOwner(_: Void = ()) -> String {
        return NSLocalizedString("eventMemberMenuItem.makeOwner", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Сегодня
      static func newEventTodayButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.todayButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Создание события
      static func newEventTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Создать событие
      static func newEventMainActionTitle(_: Void = ()) -> String {
        return NSLocalizedString("newEvent.mainAction.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Частые игры
      static func searchGameSectionsOfften(_: Void = ()) -> String {
        return NSLocalizedString("searchGame.sections.offten", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _ActiveEventCell.validate()
      try _EventDetailsMemberCell.validate()
      try _InvitedEventCell.validate()
      try _NewEventGameCell.validate()
      try _NewEventMemberCell.validate()
    }
    
    struct _ActiveEventCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = ActiveEventCell
      
      let bundle = R.hostingBundle
      let identifier = "ActiveEventCell"
      let name = "ActiveEventCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ActiveEventCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ActiveEventCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.arrowDown", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.arrowDown' is used in nib 'ActiveEventCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'ActiveEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'ActiveEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "shape.background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'shape.background' is used in storyboard 'ActiveEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'ActiveEventCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct _AvatarView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "AvatarView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _EventCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = EventCell
      
      let bundle = R.hostingBundle
      let identifier = "EventCell"
      let name = "EventCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EventCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EventCell
      }
      
      fileprivate init() {}
    }
    
    struct _EventDetailsMemberCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EventDetailsMemberCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EventDetailsMemberCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EventDetailsMemberCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.normal.crown", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.normal.crown' is used in nib 'EventDetailsMemberCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'EventDetailsMemberCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.secondary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.secondary' is used in storyboard 'EventDetailsMemberCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "yellow", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'yellow' is used in storyboard 'EventDetailsMemberCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct _InventedHeaderView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "InventedHeaderView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _InvitationsHeaderCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "InvitationsHeaderCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> InvitationsHeaderCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? InvitationsHeaderCell
      }
      
      fileprivate init() {}
    }
    
    struct _InvitedEventCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "InvitedEventCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.details", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.details' is used in nib 'InvitedEventCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "status.normal.ontime", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'status.normal.ontime' is used in nib 'InvitedEventCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'InvitedEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "green", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'green' is used in storyboard 'InvitedEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "shape.background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'shape.background' is used in storyboard 'InvitedEventCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'InvitedEventCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct _NewEventGameCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = NewEventGameCell
      
      let bundle = R.hostingBundle
      let identifier = "NewEventGameCell"
      let name = "NewEventGameCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> NewEventGameCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewEventGameCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "status.small.ontime", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'status.small.ontime' is used in nib 'NewEventGameCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'NewEventGameCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'NewEventGameCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct _NewEventMemberCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = NewEventMemberCell
      
      let bundle = R.hostingBundle
      let identifier = "NewEventMemberCell"
      let name = "NewEventMemberCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> NewEventMemberCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewEventMemberCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "status.small.ontime", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'status.small.ontime' is used in nib 'NewEventMemberCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'NewEventMemberCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'NewEventMemberCell', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'NewEventMemberCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct _SearchEmptyResultCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = SearchEmptyResultCell
      
      let bundle = R.hostingBundle
      let identifier = "SearchEmptyResultCell"
      let name = "SearchEmptyResultCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SearchEmptyResultCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SearchEmptyResultCell
      }
      
      fileprivate init() {}
    }
    
    struct _SearchGameCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = SearchGameCell
      
      let bundle = R.hostingBundle
      let identifier = "SearchGameCell"
      let name = "SearchGameCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SearchGameCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SearchGameCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try eventDetails.validate()
      try eventsList.validate()
      try launchScreen.validate()
      try newEvent.validate()
      try searchGame.validate()
      try searchMembers.validate()
    }
    
    struct eventDetails: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = EventDetailsViewController
      
      let bundle = R.hostingBundle
      let eventDetailsViewController = StoryboardViewControllerResource<EventDetailsViewController>(identifier: "EventDetailsViewController")
      let name = "EventDetails"
      
      func eventDetailsViewController(_: Void = ()) -> EventDetailsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: eventDetailsViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.arrowDown", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.arrowDown' is used in storyboard 'EventDetails', but couldn't be loaded.") }
        if UIKit.UIImage(named: "common.plus", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.plus' is used in storyboard 'EventDetails', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "action.accent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'action.accent' is used in storyboard 'EventDetails', but couldn't be loaded.") }
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'EventDetails', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'EventDetails', but couldn't be loaded.") }
          if UIKit.UIColor(named: "shape.background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'shape.background' is used in storyboard 'EventDetails', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'EventDetails', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.secondary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.secondary' is used in storyboard 'EventDetails', but couldn't be loaded.") }
        }
        if _R.storyboard.eventDetails().eventDetailsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'eventDetailsViewController' could not be loaded from storyboard 'EventDetails' as 'EventDetailsViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct eventsList: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = EventsListViewController
      
      let bundle = R.hostingBundle
      let eventsListViewController = StoryboardViewControllerResource<EventsListViewController>(identifier: "EventsListViewController")
      let name = "EventsList"
      
      func eventsListViewController(_: Void = ()) -> EventsListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: eventsListViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.plus", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.plus' is used in storyboard 'EventsList', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "action.accent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'action.accent' is used in storyboard 'EventsList', but couldn't be loaded.") }
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'EventsList', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'EventsList', but couldn't be loaded.") }
        }
        if _R.storyboard.eventsList().eventsListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'eventsListViewController' could not be loaded from storyboard 'EventsList' as 'EventsListViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct newEvent: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NewEventViewController
      
      let bundle = R.hostingBundle
      let name = "NewEvent"
      let newEventViewController = StoryboardViewControllerResource<NewEventViewController>(identifier: "NewEventViewController")
      
      func newEventViewController(_: Void = ()) -> NewEventViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: newEventViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common.calendar", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common.calendar' is used in storyboard 'NewEvent', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "action.accent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'action.accent' is used in storyboard 'NewEvent', but couldn't be loaded.") }
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'NewEvent', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'NewEvent', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.primary' is used in storyboard 'NewEvent', but couldn't be loaded.") }
          if UIKit.UIColor(named: "text.secondary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text.secondary' is used in storyboard 'NewEvent', but couldn't be loaded.") }
        }
        if _R.storyboard.newEvent().newEventViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'newEventViewController' could not be loaded from storyboard 'NewEvent' as 'NewEventViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct searchGame: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SearchGameViewController
      
      let bundle = R.hostingBundle
      let name = "SearchGame"
      let searchGameViewController = StoryboardViewControllerResource<SearchGameViewController>(identifier: "SearchGameViewController")
      
      func searchGameViewController(_: Void = ()) -> SearchGameViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: searchGameViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'SearchGame', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'SearchGame', but couldn't be loaded.") }
        }
        if _R.storyboard.searchGame().searchGameViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'searchGameViewController' could not be loaded from storyboard 'SearchGame' as 'SearchGameViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct searchMembers: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SearchMembersViewController
      
      let bundle = R.hostingBundle
      let name = "SearchMembers"
      let searchMembersViewController = StoryboardViewControllerResource<SearchMembersViewController>(identifier: "SearchMembersViewController")
      
      func searchMembersViewController(_: Void = ()) -> SearchMembersViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: searchMembersViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'background' is used in storyboard 'SearchMembers', but couldn't be loaded.") }
          if UIKit.UIColor(named: "block", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'block' is used in storyboard 'SearchMembers', but couldn't be loaded.") }
        }
        if _R.storyboard.searchMembers().searchMembersViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'searchMembersViewController' could not be loaded from storyboard 'SearchMembers' as 'SearchMembersViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
